USE [master]
GO

/****** Object:  Database [BugTrackerDB]    Script Date: 13 mar 2025 12:08:29 ******/
CREATE DATABASE [BugTrackerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BugTrackerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BugTrackerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BugTrackerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BugTrackerDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BugTrackerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BugTrackerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BugTrackerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BugTrackerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BugTrackerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BugTrackerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BugTrackerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BugTrackerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BugTrackerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BugTrackerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BugTrackerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BugTrackerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BugTrackerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BugTrackerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BugTrackerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BugTrackerDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BugTrackerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BugTrackerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BugTrackerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BugTrackerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BugTrackerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BugTrackerDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BugTrackerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BugTrackerDB] SET RECOVERY FULL 
GO

ALTER DATABASE [BugTrackerDB] SET  MULTI_USER 
GO

ALTER DATABASE [BugTrackerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BugTrackerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BugTrackerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BugTrackerDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BugTrackerDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BugTrackerDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BugTrackerDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BugTrackerDB] SET  READ_WRITE 
GO

